export const SET_COUNTIES = 'SET_COUNTIES';
export const SET_COUNTY = 'SET_COUNTY';
export const SET_YEARDATA = 'SET_YEARDATA';
export const ADD_DATA_TO_DISPLAY = 'ADD_DATA_TO_DISPLAY';
export const REMOVE_DATA_TO_DISPLAY = 'REMOVE_DATA_TO_DISPLAY';
